services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "mysql://srikanth:Robinhood456@host.docker.internal:3306/tsp_payroll_cloud"
      NEXTAUTH_URL: "http://localhost:3000"
      NEXTAUTH_SECRET: "JIONTHAKJFJOADTHLHLKL"
    ports:
      - "3000:3000"
    restart: unless-stopped
